# Generated by Django 2.2.17 on 2020-12-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsform',
            old_name='country',
            new_name='error_type',
        ),
        migrations.RenameField(
            model_name='eventsform',
            old_name='email',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='eventsform',
            old_name='name',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='eventsform',
            name='phone',
        ),
    ]
